### ISSUE TITLE
Trying to extract flash1.psarc extracts files, but gives an error

### ISSUE THREAD

**Issue by dilirity** [rm-NoobInCoding/UnPSARC#1]
File:
`steam\Uncharted Legacy of Thieves Collection\Uncharted4_data\build\pc\main\flash1.psarc`

Just decide to share.

![image](https://user-images.githubusercontent.com/11799079/197015447-cb181d9e-99bb-4079-9bd5-b960812910d0.png)

**Comment by rm-NoobInCoding** [comment]
The uncompressed size defined for this file in the archive is wrong
So as a result, I can't do anything
