### ISSUE TITLE
Ghost of Tsushima PSARC Issues

### ISSUE THREAD

**Issue by DanialPahlavan** [rm-NoobInCoding/UnPSARC#10]
## Game Name:
Ghost of Tsushima

## Issue Description:
When attempting to unpack the .psarc files for the English audio content of Ghost of Tsushima using the UnPSARC tool, I am met with an error message indicating a problem with the file format.

## Steps to Reproduce:
Run UnPSARC tool.
Attempt to unpack lang_english_audio.psarc.
### Expected Behavior:
The tool should successfully unpack the .psarc file without errors.

### Actual Behavior:
The unpacking process is interrupted by an error message, as detailed below.

## Error Message:
UnPSARC (Archive Tool For PlayStation Archive files 'PSARC')
By NoobInCoding

Unpacking lang_english_audio.psarc...
Archive is Compressed (DSAR), trying to Decompress...

Unhandled Exception: System.Exception: Not valid PSARC file! Magic:SAR

## Additional Information:
The archive format is identified as DSAR, which stands for DirectStorage Archive.
The issue seems to be related to the file’s magic number not matching the expected PSARC format.
I would appreciate any guidance or updates on the resolution of this issue. Thank you for your tools .

**Comment by DanialPahlavan** [comment]
## Reproduce for lang_japanese_audio.psar 

UnPSARC (Archive Tool For PlayStation Archive files 'PSARC')
By NoobInCoding
https://github.com/rm-NoobInCoding/UnPSARC

Unpacking lang_japanese_audio.psarc...
Archive is Compressed (DSAR), trying to Decompress...

Unhandled Exception: System.Exception: Not valid PSARC file! Magic:SAR

**Comment by DanialPahlavan** [comment]
uncompress bitmaps check : 
## gapack_bitmaps_a.psarc ✅
## gapack_bitmaps_b.psarc ✅
## gapack_bitmaps_c.psarc ❌ 
 ---bitmaps\cliff_arch_a_ag.msac.d.0.sps Cannot Exported! Error:Illegal rep dist code
## gapack_bitmaps_d.psarc ✅
## gapack_bitmaps_e.psarc ✅
## gapack_bitmaps_f.psarc ✅
## gapack_bitmaps_g.psarc ✅
## gapack_bitmaps_h.psarc ✅
## gapack_bitmaps_i.psarc ✅
## gapack_bitmaps_j.psarc ✅
## gapack_bitmaps_k.psarc ✅
## gapack_bitmaps_l.psarc ✅
## gapack_bitmaps_n.psarc ✅
## gapack_bitmaps_m.psarc ❌
[2464] ---bitmaps\monk_tengu_mask_necklace_mtl.msac.g.00c27426aaa11c3229a0fab6c356f09e.sps Cannot Exported! Error:Encountered invalid codelength 0

## gapack_bitmaps_o.psarc ✅
## gapack_bitmaps_p.psarc ✅
## gapack_bitmaps_r.psarc ✅
## gapack_bitmaps_s.psarc ✅
## gapack_bitmaps_t.psarc ✅
## gapack_bitmaps_u.psarc ✅
## gapack_bitmaps_v.psarc ✅
## gapack_bitmaps_w.psarc ✅
## gapack_bitmaps_x.psarc ✅
## gapack_bitmaps_y.psarc ✅

**Comment by DanialPahlavan** [comment]
# uncompress music check

## music_a✅
## music_b❌
---506116104.wem Cannot Exported! Error:Index was outside the bounds of the array.
## music_c✅
## music_d✅
## music_e✅

**Comment by DanialPahlavan** [comment]
# uncompress misc check 
## gapack_misc_a ✅
## gapack_misc_b ✅
## gapack_misc_c✅
## gapack_misc_d✅
## gapack_misc_e✅
## gapack_misc_f✅
## gapack_misc_g✅
## gapack_misc_h✅
## gapack_misc_i✅
## gapack_misc_j✅
## gapack_misc_k✅
## gapack_misc_l✅
## gapack_misc_m
[2932] ---m_sp_otsuna_coward_telltruth_ja#tandem#1.xpps Cannot Exported! Error:Unknown block type 7
## gapack_misc_n✅
## gapack_misc_p✅
## gapack_misc_r✅
## gapack_misc_s✅
## gapack_misc_t✅
## gapack_misc_w✅
## gapack_misc_y✅

**Comment by DanialPahlavan** [comment]
امیدوارم این ها برایتان مفید باشد . 😘

**Comment by rm-NoobInCoding** [comment]
ممنون. توی نسخه جدید پشتیبانی از chunk های بدون فشرده سازی و padding رو به DSAR Decompressor اضافه کردم. احتمالا الان باید lang_english_audio.psarc رو بخونه

Translate:

Thanks!
I added support for uncompressed chunks and padding chunks to DSAR Decompressor. Tool should probably read lang_english_audio.psarc now

**Comment by DanialPahlavan** [comment]
**Version 2.3 - Remaining Files decompress Check**

### Status Summary
- **English Audio Pack**: ✅ Successfully exported all files.
- **Japanese Audio Pack**: ⚠️ Encountered issues with one file.
- **Bitmaps Pack C**: ⚠️ Encountered issues with one file.
- **Bitmaps Pack M**: ⚠️ Encountered issues with one file.
- **Music Pack B**: ⚠️ Encountered issues with one file.
- **Miscellaneous Pack M**: ⚠️ Encountered issues with one file.

### Detailed Report

#### lang_english_audio
- All files exported successfully.

#### lang_japanese_audio
- Issue with file `[22676]`: `---s_gp_shimura_darkness_rift_a10.wem`
  - **Error**: Broken uncompressed block.
  - **Status**: 29,378 of 29,379 files exported.

#### gapack_bitmaps_c.psarc
- Issue with file `[71]`: `---bitmaps\cliff_arch_a_ag.msac.d.0.sps`
  - **Error**: Illegal rep dist code.
  - **Status**: 2,840 of 2,841 files exported.

#### gapack_bitmaps_m.psarc
- Issue with file `[2464]`: `---bitmaps\monk_tengu_mask_necklace_mtl.msac.g.00c27426aaa11c3229a0fab6c356f09e.sps`
  - **Error**: Encountered invalid codelength 0.
  - **Status**: 2,734 of 2,735 files exported.

#### music_b
- Issue with file `[382]`: `---506116104.wem`
  - **Error**: Index was outside the bounds of the array.
  - **Status**: 481 of 482 files exported.

#### gapack_misc_m
- Issue with file `[2932]`: `---m_sp_otsuna_coward_telltruth_ja#tandem#1.xpps`
  - **Error**: Unknown block type 7.
  - **Status**: 5,182 of 5,183 files exported.
