### ISSUE TITLE
File packaging problem.

### ISSUE THREAD

**Issue by dinhhoangthang** [rm-NoobInCoding/UnPSARC#18]
Hello!
I discovered a file packaging problem, I unpacked the flash1.psarc file of the game "Uncharted Legacy of Thieves Collection" after editing the font, then I repackaged the file, the file is 15.8mb , The game works without any problem.
The problem occurs when I unpack and repackage without editing any files inside the flash1.psarc file but the capacity after compression is reduced to 15.2 mb. Entering the game has an error that does not display text.

**Comment by rm-NoobInCoding** [comment]
I made some changes and i think this bug is fixed in 2.5.0
Please test new version

**Comment by dinhhoangthang** [comment]
Thank you, I tested it on version 2.5, it works perfectly without any problems.

Sorry, to bother you a bit. I'm having an issue about "NaughtyDog Localization Tool", but I can't create a new issue. Looking forward to your help, thank you very much.
