### ISSUE TITLE
unpacking error with data2.psarc [The Legend of Heroes: Trails of Cold Steel (PS4)]

### ISSUE THREAD

**Issue by modusc896d352** [rm-NoobInCoding/UnPSARC#19]
[TLOH:TOCS1](https://en.wikipedia.org/wiki/The_Legend_of_Heroes:_Trails_of_Cold_Steel) has three psarc files: **data.psarc**, **data2.psarc** and **dlc.psarc**, respectively.

every psarc file but the second one was unpacked without issue.
second one tho has put out an error message:
```
Exceção Sem Tratamento: System.Exception: Archive Contains a hash which is not in filenames table: 21-83-6C-C3-57-75-0C-6F-20-40-45-73-3A-6C-74-B0
   em UnPSARC.Archive.Unpack(Stream ArchiveRaw, String Folder)
   em UnPSARC.Program.UnpackArchiveFile(String inputPath, String outputDirectory)
   em UnPSARC.Program.Main(String[] args)
```

**Comment by rm-NoobInCoding** [comment]
Please upload your file somewhere and send its link

**Comment by modusc896d352** [comment]
uploading it right away!

**Comment by modusc896d352** [comment]
well, seems like i can't really send this file (even as a link) _to you_ so i'll just leave it here instead.
[data2.psarc](https://qiwi.gg/file/8z7i5956-data2)

link will vanish anyway as it contains copyrighted assets from the PS4 game so grab the file while it's on-line!
