### ISSUE TITLE
Xpps localization ghost of tsushima

### ISSUE THREAD

**Issue by jack-moder** [rm-NoobInCoding/UnPSARC#26]
Dear noobln I find localization files in gapack_misc_l.psarc but it needs a tool to edit it, you can make a tool for it 🙏🏻
File type format : xpps

**Comment by jack-moder** [comment]
Please make a tool for xpps (language files) too, it's a pity that this good tool of yours remains incomplete, and you help us a lot, and we will also donate for you.

**Comment by rm-NoobInCoding** [comment]
For God sake please read the first lines of readme
