### ISSUE TITLE
PSARC files are unpacked into SPS files

### ISSUE THREAD

**Issue by OrionNuble** [rm-NoobInCoding/UnPSARC#8]
Hi,

After unpacking a *.psarc file, all the unpacked files are in *.sps format. I don't know how would this be useful since I couldn't find any information about this file format.

Context: I'm using this on Ghost of Tsushima files

I thought I could ask about it here since it is mentioned that this was tested on Ghost of Tsushima.

Any help is appreciated.

**Comment by Foul-Tarnished** [comment]
That's not an issue, this tool unpacked as expected

Use this to export ``.sps`` to ``.dds`` or other picture format
https://github.com/SilverEzredes/fmt_GoT_SPS-Noesis-Plugin

For xpps and xmesh and others, nobody knows yet.
Join ModdingHaven discord server for more infos
