### ISSUE TITLE
Repacking GoT vanilla assets breaks rendering

### ISSUE THREAD

**Issue by Foul-Tarnished** [rm-NoobInCoding/UnPSARC#9]
- I unpacked ``gapack_meshes.psarc``
- I repacked the folder to a new ``gapack_meshes.psarc``, with the same game vanilla content.
- Replace the file in the game install
- Rendering is really broken, see : 
Also, the file went from 850MB to ~1.34GB

https://github.com/rm-NoobInCoding/UnPSARC/assets/107711110/890937ca-9d93-4a26-adb7-ddd722b4a10f

I didn't try with psarc containing only .sps bitmaps, or misc psarc with only .xpps
Maybe only meshes are affected, maybe not

This was done with UnPSARC 2.0, considering 2.1 issue (0kb files size) see #7

**Comment by rm-NoobInCoding** [comment]
I tried this with my game and everything work perfectly fine. Please test this on other pc

**Comment by Foul-Tarnished** [comment]
> I tried this with my game and everything work perfectly fine. Please test this on other pc

Which version did you use ?
I also tried with latest 2.3, same issue

Are you sure you're following my steps ?
drag 850MB ``gapack_meshes.psarc`` on ``UnPSARC.exe``, and you get a folder named ``gapack_meshes_Unpacked``
then drag the ``gapack_meshes_Unpacked`` folder on ``UnPSARC.exe`` and it will create an archive ``gapack_meshes_Unpacked.psarc`` that is 1.34GB !

this will cause the rendering issues above.

**Comment by rm-NoobInCoding** [comment]
The reason for the size difference is that the original file are compressed, but repacked archive is without compression.
Anyway, I'm investigating this problem, but I think if someone else tests it, we can draw conclusions more easily.

**Comment by Foul-Tarnished** [comment]
This probably was an issue on 2.0 only, fixed in 2.1, but only visible since 2.2 (because 2.1 had major export bug)

2.3 works fine, no rendering issue
only issue is no compression (if we modded all archive, that would probably make the game 100gb instead of 50gb) but not really an issue if we manage to load custom .psarc into the game
